#!/bin/bash

function link_dotfiles() {
    # Get all dotfiles
    FILES=$(find . -type f -name ".*")
    for f in $FILES
    do 
	echo "Symlinking $f file..."
	ln -s -f "$(pwd)/$f" ~/$f
    done
}

read -p "This may overwrite existing dotfiles in your home directory. Are you sure? (y/n) " -n 1
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    link_dotfiles
fi

unset link_dotfiles
